# Generated by Django 3.2.18 on 2023-04-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstaStampResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(max_length=255)),
                ('exist', models.BooleanField(default=False)),
                ('likes', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=50)),
                ('friends', models.CharField(max_length=50)),
            ],
        ),
    ]
