# Generated by Django 3.0 on 2023-04-21 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstaKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': '인스타 키워드',
            },
        ),
        migrations.CreateModel(
            name='InstaStampResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_insta', models.IntegerField(default=0)),
                ('total_likes', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
                ('total_friends', models.IntegerField(default=0)),
                ('hashtags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insta_admin', to='insta_admin.InstaKeywords')),
            ],
        ),
        migrations.CreateModel(
            name='InstaSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_url', models.CharField(max_length=255)),
                ('events_name', models.CharField(max_length=120)),
                ('events_date', models.CharField(max_length=120)),
                ('hashtags', models.ManyToManyField(related_name='insta_events', to='insta_admin.InstaKeywords')),
            ],
        ),
    ]
