# Generated by Django 3.2.18 on 2023-04-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instastampresult',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='instastampresult',
            name='exist',
        ),
        migrations.RemoveField(
            model_name='instastampresult',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='instastampresult',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='instastampresult',
            name='name',
        ),
        migrations.RemoveField(
            model_name='instastampresult',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='instastampresult',
            name='url',
        ),
        migrations.AddField(
            model_name='instastampresult',
            name='total_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instastampresult',
            name='total_friends',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instastampresult',
            name='total_insta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instastampresult',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
