# Generated by Django 3.0 on 2023-04-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instasetting',
            name='hashtags_selected',
            field=models.IntegerField(default=0),
        ),
    ]
