# Generated by Django 3.0 on 2023-04-22 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta_admin', '0002_instasetting_hashtags_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='instakeywords',
            name='insta_setting_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insta_keywords', to='insta_admin.InstaSetting'),
        ),
        migrations.AlterField(
            model_name='instasetting',
            name='hashtags_selected',
            field=models.IntegerField(default=1),
        ),
    ]
