# Generated by Django 3.0 on 2023-04-21 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insta_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaStampList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insta_name', models.CharField(max_length=50)),
                ('insta_url', models.CharField(max_length=255)),
                ('insta_ref', models.CharField(max_length=255, unique=True)),
                ('insta_date', models.CharField(blank=True, max_length=50, null=True)),
                ('insta_stamp', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('likes_cnt', models.IntegerField(blank=True, default=0, null=True)),
                ('comments_cnt', models.IntegerField(blank=True, default=0, null=True)),
                ('friends_cnt', models.IntegerField(blank=True, default=0, null=True)),
                ('hashtags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insta_stamp', to='insta_admin.InstaKeywords')),
            ],
        ),
    ]
