# Generated by Django 3.2.18 on 2023-04-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstaStampList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insta_name', models.CharField(max_length=50)),
                ('insta_url', models.CharField(max_length=255)),
                ('insta_ref', models.CharField(max_length=255, unique=True)),
                ('insta_date', models.CharField(blank=True, max_length=50, null=True)),
                ('insta_stamp', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('exist', models.BooleanField(default=False)),
                ('likes_cnt', models.IntegerField(default=0)),
                ('comments_cnt', models.IntegerField(default=0)),
                ('friends_cnt', models.IntegerField(default=0)),
            ],
        ),
    ]
