# Generated by Django 3.2.18 on 2023-04-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_stamp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instastamplist',
            name='exist',
        ),
        migrations.AlterField(
            model_name='instastamplist',
            name='comments_cnt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='instastamplist',
            name='friends_cnt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='instastamplist',
            name='likes_cnt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
